[tox]
envlist = py38, py39, py310, py311, py312, py313
isolated_build = True

[testenv]
deps =
    pytest
    babel
    pytest-cov  # 新增
commands =
    pytest --cov=zxcvbn --cov-report=xml:coverage.xml  # 修改
    python tests/test_compatibility.py tests/password_expected_value.json
    python tests/test_zxcvbn_instance_speed.py
[testenv:.pkg]
deps =
    babel
allowlist_externals = pybabel
commands_pre =
    pybabel compile -d zxcvbn/locale
